const {spawn}=require("child_process");const fs=require("fs");const path=require("path");
const CH="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";const PORT=9391;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const prof=fs.mkdtempSync("/tmp/cdp-");
 const ch=spawn(CH,["--headless=new","--disable-gpu","--remote-debugging-port="+PORT,"--user-data-dir="+prof,"about:blank"],{stdio:"ignore"});
 let tabs=null;for(let i=0;i<40;i++){try{tabs=await (await fetch("http://127.0.0.1:"+PORT+"/json")).json();if(tabs.length)break;}catch(e){}await sleep(250);}
 const ws=new WebSocket(tabs.find(t=>t.type==="page").webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener("open",r));
 let id=0;const pend={};const errs=[];
 ws.addEventListener("message",ev=>{const m=JSON.parse(ev.data);
  if(m.method==="Runtime.exceptionThrown")errs.push(String(m.params.exceptionDetails.exception&&m.params.exceptionDetails.exception.description||"").slice(0,160));
  if(m.id&&pend[m.id]){pend[m.id](m.result||m);delete pend[m.id];}});
 const send=(m,p={})=>new Promise(r=>{const i=++id;pend[i]=r;ws.send(JSON.stringify({id:i,method:m,params:p}));});
 const ev=async x=>{const r=await send("Runtime.evaluate",{expression:x,awaitPromise:true,returnByValue:true});return r.result?r.result.value:r;};
 const shot=async n=>{const r=await send("Page.captureScreenshot",{format:"png"});fs.writeFileSync(n,Buffer.from(r.data,"base64"));};
 await send("Runtime.enable");await send("Page.enable");
 await send("Emulation.setDeviceMetricsOverride",{width:390,height:800,deviceScaleFactor:1.5,mobile:true});
 await send("Page.navigate",{url:"file://"+path.resolve("t.html")});await sleep(1700);
 const out=[];const ok=(n,c,d)=>out.push((c?"OK   ":"FAIL ")+n+(d!==undefined?"  ("+d+")":""));
 await ev('localStorage.clear();draw();1');
 ok("設定に「フラッシュ暗記」ボタンがある", (await ev('!!$("flashStart")')), await ev('$("flashStart").textContent'));
 await shot("m1_set.png");
 await ev('sources=["kanto"];current="kt1";count=5;flSpeed=2;draw();$("flashStart").click();1');await sleep(500);
 ok("フラッシュ暗記が始まる", (await ev('mode'))==="flash" && (await ev('!!document.querySelector(".fl-card")')));
 ok("最初は答えが隠れている", !(await ev('document.querySelector(".fl-a").classList.contains("show")')));
 await shot("m2_q.png");
 await sleep(1700);
 ok("しばらくすると答えが出る", (await ev('document.querySelector(".fl-a").classList.contains("show")')), await ev('document.querySelector(".fl-a").textContent'));
 await shot("m3_a.png");
 await sleep(1500);
 ok("自動で次の問題へ進む", (await ev('fl.i'))>=1, "i="+await ev('fl.i'));
 await ev('flPause(true);1');await sleep(300);
 const at=await ev('fl.i');
 await sleep(1500);
 ok("一時停止すると止まる", (await ev('fl.i'))===at, "i="+at);
 await ev('flGo(1);1');await sleep(200);
 ok("「つぎ」で進める", (await ev('fl.i'))===at+1);
 await ev('flGo(-1);1');await sleep(200);
 ok("「まえ」で戻れる", (await ev('fl.i'))===at);
 await ev('flPause(false);1');
 for(let i=0;i<60 && (await ev('fl && fl.phase'))!=="end";i++)await sleep(300);
 ok("最後まで行くと終わりの画面", (await ev('fl.phase'))==="end" && /おわり/.test(await ev('document.querySelector("#play h2").textContent')), await ev('document.querySelector("#play h2").textContent'));
 await shot("m4_end.png");
 ok("◯△の記録はつかない", (await ev('Object.keys(marks).length'))===0);
 await ev('[...document.querySelectorAll("#play .btn")].find(b=>b.textContent==="1問ずつ答える").click();1');await sleep(500);
 ok("そのまま1問ずつに切り替えられる", (await ev('mode'))==="card" && (await ev('sess.items.length'))===5);
 await ev('history.back();1');await sleep(600);
 ok("戻るで設定にもどる", (await ev('mode'))==="list" && !(await ev('$("bar").hidden')));
 await ev('sources=["chubu"];current="c3";count=3;draw();$("flashStart").click();1');await sleep(700);
 ok("地図つきの分野でも地図が出る", (await ev('!!document.querySelector(".fl-map .cmap")')));
 await shot("m5_map.png");
 await ev('$("showList").click();1');await sleep(400);
 ok("一覧に戻すとタイマーが止まる", (await ev('mode'))==="list" && (await ev('fl===null'))&&(await ev('flTimer===null')));
 out.push(errs.length?("ERR "+errs.join(" | ")):"OK   エラーなし");
 console.log(out.join("\n"));ws.close();ch.kill();
})().catch(e=>{console.error(e);process.exit(1);});
