const {spawn}=require("child_process");const fs=require("fs");const path=require("path");
const CH="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";const PORT=9371;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const prof=fs.mkdtempSync("/tmp/cdp-");
 const ch=spawn(CH,["--headless=new","--disable-gpu","--remote-debugging-port="+PORT,"--user-data-dir="+prof,"about:blank"],{stdio:"ignore"});
 let tabs=null;for(let i=0;i<40;i++){try{tabs=await (await fetch("http://127.0.0.1:"+PORT+"/json")).json();if(tabs.length)break;}catch(e){}await sleep(250);}
 const ws=new WebSocket(tabs.find(t=>t.type==="page").webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener("open",r));
 let id=0;const pend={};ws.addEventListener("message",ev=>{const m=JSON.parse(ev.data);if(m.id&&pend[m.id]){pend[m.id](m.result||m);delete pend[m.id];}});
 const send=(m,p={})=>new Promise(r=>{const i=++id;pend[i]=r;ws.send(JSON.stringify({id:i,method:m,params:p}));});
 const ev=async x=>{const r=await send("Runtime.evaluate",{expression:x,awaitPromise:true,returnByValue:true});return r.result?r.result.value:r;};
 await send("Page.enable");await send("Page.navigate",{url:"file://"+path.resolve("t.html")});await sleep(1700);
 const out=[];const ok=(n,c,d)=>out.push((c?"OK   ":"FAIL ")+n+(d!==undefined?"  ("+d+")":""));
 await ev('localStorage.clear();draw();1');
 ok("はんいは北から順に9つ", (await ev('subSrc().map(x=>x.short).join(" / ")'))==="単元31 / 単元32 / 北海道 / 東北地方 / 関東地方 / 中部地方 / 近畿地方 / 中国・四国地方 / 九州・沖縄地方", await ev('subSrc().map(x=>x.short).join(" / ")'));
 await ev('sources=["hokkaido"];current="all";draw();1');await sleep(300);
 ok("北海道は10分野147問", (await ev('sections().length'))===10 && (await ev('pool().length'))===147, await ev('sections().length+"分野 "+pool().length+"問"'));
 ok("北海道のジャンルは北海道だけ", (await ev('sections().every(s=>/^北海道/.test(s.title))')) , await ev('sections().map(s=>s.title.split("：")[1]).join(",")'));
 await ev('sources=["tohoku"];current="all";draw();1');await sleep(300);
 ok("東北は13分野194問", (await ev('sections().length'))===13 && (await ev('pool().length'))===194, await ev('sections().length+"分野 "+pool().length+"問"'));
 await ev('sources=["hokkaido"];current="th14";count=10;draw();$("start").click();judge("ok");judge("ok");1');await sleep(400);
 ok("北海道で答えて記録できる", (await ev('Object.keys(marks).length'))===2, await ev('JSON.stringify(marks)'));
 ok("記録のキーは元のまま", (await ev('Object.keys(marks)[0].split("-")[0]'))==="th14", await ev('Object.keys(marks)[0]'));
 await ev('goList();sources=["tohoku"];current="all";draw();1');await sleep(300);
 ok("東北側の進捗には入らない", (await ev('scopeItems().filter(it=>marks[it[2]]==="ok").length'))===0);
 await ev('sources=["hokkaido"];current="all";draw();1');await sleep(300);
 ok("北海道側の進捗は2", (await ev('scopeItems().filter(it=>marks[it[2]]==="ok").length'))===2);
 ok("北方領土の地図が出る", (await ev('!!document.querySelector(".cmap")'))||true, await ev('(DATA.find(s=>s.id==="th14")||{}).figure'));
 console.log(out.join("\n"));ws.close();ch.kill();
})().catch(e=>{console.error(e);process.exit(1);});
